### ISSUE TITLE
Compatibility issues with presentations section in Firefox

### ISSUE THREAD

**Issue by adamkucharski** [epiverse-trace/epiverse-trace.github.io#118]
Currently, clicking on a link on the [presentations page](https://epiverse-trace.github.io/presentations.html) (e.g. Global Health Resilience Research Visit) when using Firefox automatically downloads the PDF slides. On the relevant presentation page, the slides also don't display in the iframe window. These problems don't seem to occur with Chrome – not sure if it's a constraint of the package we use. Although may not be major problem, given how likely other users are to encounter problem (think about 85% use Chrome and Safari).

**Comment by Bisaloo** [comment]
I'm using Firefox and I don't have this issue. I believe this is caused by non-standards settings on your end.

Try starting Firefox with a clean profile and you should be able to verify if the problem lies with your config or not: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles.

**Comment by adamkucharski** [comment]
Thanks. Realised that it requires PDF setting in Applications to be 'Open in Firefox', which I'd disabled (as journals often have their own viewer).
