### ISSUE TITLE
Blog post for major (or minor) releases only

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiverse-trace.github.io#135]
The automated release blog post workflow (introduced in #95 if I'm not mistaken) releases every Epiverse-TRACE package release, as evidenced by the recent [post from {bpmodels} v0.3.0 -> v0.3.1](https://epiverse-trace.github.io/posts/bpmodels_v0.3.1/). I assume the default setting for the script that checks for releases is not check which version is bumped. 

I propose we change this to only automatically release blog posts when the release bumps the major version (i.e. first number in version). 

If not, an option to not post about a release should be given to the maintainer of each package at the point of release. I believe that under an agile framework, frequent patch and minor releases are beneficial and a blog post about each one seems like we will be spamming the readership. It also dilutes the hard work and time going into other blog posts which I think are much more valuable to the community. 

An extra point (which could be converted into a separate issue if wanted) I would have three tabs within the Blog section of the website, 1) all posts, 2) Epiverse articles, 3) releases. This would allow quick filtering out of release posts.

**Comment by jamesmbaazam** [comment]
> An extra point (which could be converted into a separate issue if wanted) I would have three tabs within the Blog section of > the website, 1) all posts, 2) Epiverse articles, 3) releases. This would allow quick filtering out of release posts.

I think this solution is great and would remove the need to only release posts for certain version increments. Restricting it to major releases alone might be too high a threshold. I would agree with releasing posts for minor and major releases and important patch releases, considering that we don't actually do a lot of releases.

**Comment by Bisaloo** [comment]
I agree in principle and I'm open to adding code to check the type of release before drafting a post but I don't know if it would deviate much from the current situation in practice.

Some additional elements of context before we continue this conversation:

- Automated posts are submitted as a PR rather than directly added to main for this very reason. It gives maintainers the opportunity to decide if this is worth publishing or not, as was done in the case of bpmodels: https://github.com/epiverse-trace/epiverse-trace.github.io/pull/129. This can also let maintainers decide if they'd prefer to write up a blog post themselves rather than relying on the automatically generated release notes.

> An extra point (which could be converted into a separate issue if wanted) I would have three tabs within the Blog section of the website, 1) all posts, 2) Epiverse articles, 3) releases. This would allow quick filtering out of release posts.

- Posts can already be filtered by clicking on the relevant tags in the right-hand side list.
  - All posts: https://epiverse-trace.github.io/blog.html#category= 
  - Automated release posts: https://epiverse-trace.github.io/blog.html#category=new-release 
  In particular, release posts are not tagged with `R`, which means they won't be sent to blog aggregators, such as R-bloggers since they have a policy against automatically generated content.

**Comment by joshwlambert** [comment]
> Automated posts are submitted as a PR rather than directly added to main for this very reason. It gives maintainers the opportunity to decide if this is worth publishing or not

Thanks for pointing this out, I hadn't noticed the PRs. I think this is a fine mechanism to allow maintainers to decide and the script to generate the automated posts can stay as is. However, I would appreciate if there was a general consensus that we do not publish posts for patch releases, and then major and minor can be handled on a case-by-case basis.

> Posts can already be filtered by clicking on the relevant tags in the right-hand side list

I appreciate this filtering is already possible, however, it doesn't feel as seemless as it could from a UX point of view. The currently categories, in my view, are sort of subcategories and the main delineation is whether it is a release post or written Epiverse post. Therefore, I still think having the tabs would improve the navigation and filtering of the site. If this opinion is in the minority then I'm happy to stay with the way it is now.

**Comment by jamesmbaazam** [comment]
> Therefore, I still think having the tabs would improve the navigation and filtering of the site. If this opinion is in the minority then I'm happy to stay with the way it is now.

I agree with having tabs.

**Comment by chartgerink** [comment]
Closing this issue in favor of the PR in `blueprints`: https://github.com/epiverse-trace/blueprints/pull/70

I also opened a PR for the subdiscussion here surrounding navigation: https://github.com/epiverse-trace/epiverse-trace.github.io/pull/167

You're more than welcome at both those PRs to continue the discussion 😊
