### ISSUE TITLE
Use of Avatars without agreement

### ISSUE THREAD

**Issue by TimTaylor** [epiverse-trace/epiverse-trace.github.io#333]
I always find the use of peoples GitHub avatars on the [website](https://epiverse-trace.github.io/people.html) a little odd/iffy. I've contributed my code and thoughts but not my image for the project to use. Perhaps a list of contributors would be better or, should you wish to keep the avatars, I think explicit consent for their use should be sort.

@Bisaloo / @chartgerink - I previously raised this in a Slack discussion but moving here as think it should be addressed in one way or another.

**Comment by chartgerink** [comment]
Okay, thanks. I opened a PR removing your avatar and just adding the name at the top (see #334). Design wise, I hope you can appreciate that we do not cater to personal preferences (because someone else may "hate" long lists). 

For the more general issue: I looked up the discussion on Slack and I do not see any commentary on this by others. 

Two considerations are:
1. If we consider public profile info okay to include, avatar is also okay. 
2. If we consider public profile info not okay to include w/o consent (like the avatar), we should also ask to list people as a contributor in the first place.

We have operated under consideration 1. Consideration 2 is reasonable too, and could be warranted if we learn about a wider consent wish. This does not seem to be the case at this time.

**Comment by chartgerink** [comment]
Coming back to this – for now, we added a callout to the page indicating people can request their avatars to be removed. 

If people have alternative suggestions on what to do, we invite a PR specifying this. Thanks!

**Comment by chartgerink** [comment]
There are no known legal objections regarding the use of images in this way. While I understand your concern, I believe the matter has been adequately addressed for now.
