### ISSUE TITLE
Tweet in statistical correctness post no longer rendering on website

### ISSUE THREAD

**Issue by joshwlambert** [epiverse-trace/epiverse-trace.github.io#99]

**Comment by Bisaloo** [comment]
Thanks for the report! I'm still on the fence about how to deal with this. I can easily get the tweet back from our git history but since the source cause is that the tweet author deleted their message, it might be more respectful to follow their wishes.

A possible alternative might be to anonymize the tweet but keep its content?

**Comment by joshwlambert** [comment]
I think either removing the tweet given the deletion or to anonymise is best. It might also work to paraphrase the contents of the tweet if the specific author is not relevant. I don't have a strong opinion either way and happy to go with whatever you decide.
